# Generated by Django 5.1.7 on 2025-03-13 13:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articlemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
