# Generated by Django 5.1.7 on 2025-03-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_contactmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
